### PR TITLE
Carthage supports universal frameworks now

### PR DESCRIPTION
**Pull request by kylef**
https://twitter.com/rob_rix/status/630741177461944321

/cc @neonichu

### CODE REVIEW

**Comment by kylef** [comment]
Now if only CocoaPods could :'(.

**Comment by neonichu** [comment]
``` ruby
s.prepare_command = "carthage build —no-skip-current"
```

:trollface:

**Comment by kylef** [comment]
@neonichu I mean, you can't integrate pods with universal frameworks.

**Comment by mrackwitz** [comment]
I have updated the notice independently and totally missed your PR back then (wasn't watching my own repo)

**Pull request closed without merging**
